### ISSUE TITLE
Unauthorise character in all krypton label

### ISSUE THREAD

**Issue by herledant** [Wagnerp/Krypton-NET-5.470#102]
Hello Wagnerp, Smurf,

I found a little bug when using  krypton label and button.

When i use the "&" character in the text propertie, it display an underscore instead of "&".

![image](https://user-images.githubusercontent.com/9166449/54840494-77987e80-4ccd-11e9-9945-c0245046458f.png)

Maybe some other characters could not work...

Cheers

**Comment by Wagnerp** [comment]
Hi @herledant 

To get an ampersand, you simply put `&&`

**Comment by herledant** [comment]
ok, thank's

**Comment by Smurf-IV** [comment]
That's standard winforms practice.. double ampersand is the way described in the MSDN.
