### ISSUE TITLE
Build 826 Causes Designer usage exceptions

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-5.470#104]
During the "Make more csustom Styles" the global replace has removed some of the existing style usages, e.g.

                case PaletteContentStyle.TabHighProfile:
                case PaletteContentStyle.TabStandardProfile:

                case PaletteContentStyle.HeaderSecondary:

                case PaletteContentStyle.HeaderForm:

this will cause the following to happen
![image](https://user-images.githubusercontent.com/2418812/55070686-b9834500-507e-11e9-88ac-fd153a22809e.png)

Please remove Build 826 from nuget !

**Comment by Smurf-IV** [comment]
This was caused by the build break when the following where introduced and _fixed_ quickly.. Apologies.

                case PaletteContentStyle.InputControlCustom2:
                case PaletteContentStyle.InputControlCustom3:

**Comment by Wagnerp** [comment]
Will de-list it.

**Comment by Smurf-IV** [comment]
It appears that the Exception would only by generated if `Office 2007 Base` or `Office 2010 Base` where in use for the style. (Which is mostly all !)
Currently testing the _fix_
