### ISSUE TITLE
The Office2010White is the same as Black

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-5.470#106]

**Comment by Wagnerp** [comment]
Umm... possibly the colours weren't properly carried over

**Comment by Smurf-IV** [comment]
Found by using the TestApp from the Toolkit, and also by using the designer directly.

**Comment by Wagnerp** [comment]
Yup found the problem!

**Comment by Wagnerp** [comment]
Silver is white and white is black! Should be easy to fix!!!
