### ISSUE TITLE
Office 365 White theme is incorrectly named in the designer

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-5.470#107]
![image](https://user-images.githubusercontent.com/2418812/55076714-07537980-508e-11e9-8da7-dbee5f37f2a2.png)

**Comment by Wagnerp** [comment]
Will fix

**Comment by Wagnerp** [comment]
Are you using the `KryptonManager` or `ThemeManager.cs`?

**Comment by Smurf-IV** [comment]
Image Taken from the TestApp included with Toolkit solution

**Comment by Wagnerp** [comment]
I've checked the `PaletteModeConverter` and `PaletteModeManagerConverter`, it is named correctly. Where do the strings come from?

**Comment by Smurf-IV** [comment]
It is because it missing from `PaletteModeManagerConverter`, therefore it defaults to the enum string equivalent.

**Comment by Wagnerp** [comment]
Yes, I noticed. I have to re-download the repo, as everything bugged out! :(
