### ISSUE TITLE
Office 365 White theme is missing from OnUserPreferenceChanged - KryptonManager.cs

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-5.470#110]
_paletteSparklePurple?.UserPreferenceChanged();

            _paletteOffice365Black?.UserPreferenceChanged();

            _paletteOffice365Blue?.UserPreferenceChanged();

            _paletteOffice365Silver?.UserPreferenceChanged();

            UpdateToolStripManager();
        }

**Comment by Wagnerp** [comment]
This maybe also why Office 2010 White is bugging out.
