### ISSUE TITLE
Missing Palette Features?

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-NET-5.470#113]
I have no idea where these went?

![Missing Features Win 81 1](https://user-images.githubusercontent.com/949607/55216643-359f9900-51f5-11e9-9a53-0d3ef8017d6b.png)

![Missing Features Win 10](https://user-images.githubusercontent.com/949607/55216665-418b5b00-51f5-11e9-97c4-23bbf159abbf.png)

**Comment by Smurf-IV** [comment]
I do not understand, What are you stating ? Reset's go in the Properties section, iff the value has changed:
![image](https://user-images.githubusercontent.com/2418812/55218432-00497a00-51fa-11e9-92bf-c2bcb80a073c.png)

**Comment by Wagnerp** [comment]
In older versions, the `KryptonPalette` component had a feature where the developer could assign a palette definition `xml` file to it.

**Comment by Smurf-IV** [comment]
`CustomisedKryptonPaletteFilePath` in the Designer properties ?

**Comment by Wagnerp** [comment]
No, I don't think this works, you could try by importing one of [these](https://github.com/Wagnerp/Krypton-Toolkit-Suite-Extended-NET-5.470/tree/master/Source/Palettes) theme files, but I'm not sure if something is broken with `KryptonPalette`s `Import()` method?

**Comment by Wagnerp** [comment]
Hi @Smurf-IV 

Might have found out how to do it... You need to set the `KryptonManager` `GlobalPalette` property to `KryptonPalette` **then** load in the theme files.

**Comment by Wagnerp** [comment]
Hi @Smurf-IV 

Success!!!! Well kind of...

![Annotation 2019-03-30 120704](https://user-images.githubusercontent.com/949607/55275862-63174000-52e4-11e9-9e27-bea5752b1c01.png)

**Comment by Wagnerp** [comment]
![Annotation 2019-03-30 120810](https://user-images.githubusercontent.com/949607/55275891-98239280-52e4-11e9-9380-0386649a061e.png)

**Comment by Wagnerp** [comment]
Now I can implement it properly in the extended toolkit!
