### ISSUE TITLE
Should we remove the GacUtil.exe now ?

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-5.470#114]
[Wagnerp/Krypton-NET-5.470] Page build warning

The page build completed successfully, but returned the following warning for the `master` branch:

It looks like you're using GitHub Pages to distribute binary files. We strongly suggest that you use releases to ship projects on GitHub. Releases are GitHub's way of packaging and providing software to your users. You can think of it as a replacement to using downloads to provide software. We found the following file(s) which may be a good candidate for releases: Source/Krypton Components/gacutil.exe. For more information, see https://help.github.com/en/articles/about-releases.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

**Comment by Wagnerp** [comment]
Yes, that is possibly why the build fails also. I'll do it now.

**Comment by Wagnerp** [comment]
Should I also remove `UnRegisterFromGAC.bat` &  `gacutil.exe.config`?

**Comment by Smurf-IV** [comment]
Yes, I'll Also remove the references from the help - "When" I come across them

**Comment by Wagnerp** [comment]
Ok, will do
