### ISSUE TITLE
"Sparkle Themes" do not work on test App

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-5.470#115]
Using Yesterdays code, The Sparkle themes selection in the TestApp do not work at runtime.

Note: they work when selected via the IDE Designer, so they are not broken.

**Comment by Wagnerp** [comment]
I may have forgotten to apply the Sparkle themes correctly.

**Comment by Wagnerp** [comment]
Simple fix - typos :(
