### ISSUE TITLE
[New Feature Request] Drop shadow parameters 

### ISSUE THREAD

**Issue by amagico** [Wagnerp/Krypton-NET-5.470#121]
Drop shadow is an important part of the UX. Today #56 the fixed shadow is pretty sharp and will in some use cases blend into the background. 
I suggest a feature that you can set the shadow properties: 

1. Blur  0-100 px
2. Opacity 0-100 % 
3. Offset 0-100 px
4. Offset angle 0-360° (nice to have feature)

This is a more contemporary drop shadow produced with the above parameters:

<img width="602" alt="image" src="https://user-images.githubusercontent.com/49203798/55460761-1341bd00-55f3-11e9-879d-7d3e269d1c57.png">

Many thanks!

**Comment by amagico** [comment]
Or, can we today change the current drop shadow properties ourselves? @Wagnerp :-)

**Comment by mace17** [comment]
I agree with amagico, it would be much better with 4-sides shadow, I really want this shadow, but unfortunately solutions that I found don't work.

**Comment by Wagnerp** [comment]
Hi @amagico and @mace17 

It isn't available yet, however it could be a feature for a future update. Incidentally, I was thinking about this a few weeks ago.

**Comment by amagico** [comment]
> Hi @amagico and @mace17
> 
> It isn't available yet, however it could be a feature for a future update. Incidentally, I was thinking about this a few weeks ago.

@Wagnerp that would be much appreciated and a big lift for the overall look and feel of Krypton. 
There is quite a lot of sample code out there but by overriding Krypton we encounter trouble such as window resizing (a feature that is very important to keep). A K-integrated shadow would be clever.   

Thanks a lot

**Comment by Smurf-IV** [comment]
https://www.w3schools.com/cssref/playit.asp?filename=playcss_box-shadow&preval=20px%2020px%2050px%20grey

**Comment by Smurf-IV** [comment]
I have been `playing` with several implementations and have been fighting all sorts of wonderful edge cases e.g. 
- What happens when the form is moved over a screen edge,
- What happens when the form is being used for docking,
- Max and minimising
- What about other controls (like panels)
- Pop-up windows also have shadows (i.e. menus / tooltips / popup navigator windows / etc)
- Use of DWM
- Use of Overlays
- Native Vs GDI Vs embedding WPF
- Resizing

Anyway, after all this, I think I have a design that should work for most of the above use cases for `Forms` except the other existing Krypton Controls (Initially)

**Comment by Smurf-IV** [comment]
> 
> 
> I agree with amagico, it would be much better with 4-sides shadow, I really want this shadow, but unfortunately solutions that I found don't work.

OK, I think I will drop the css styling, and allow the above to happen, i.e. specify all 4 side offsets, and a negative will impact the side that it would touch. So a standard diagonal blur would be something like (-10, -10, 10, 10)
```
    /// <param name="left">The padding size, in pixels, for the left edge.</param>
    /// <param name="top">The padding size, in pixels, for the top edge.</param>
    /// <param name="right">The padding size, in pixels, for the right edge.</param>
    /// <param name="bottom">The padding size, in pixels, for the bottom edge.</param>
```

**Comment by Wagnerp** [comment]
Hi @Smurf-IV 

Maybe it could work when the `WindowState` is restored. i.e:

``` C#
if (WindowState == FormWindowState.Normal)
{
      DrawBorderBlur(10, 10, -10, -10);
}
else
{
      DrawBorderBlur(0, 0, 0, 0);
}
```

**Comment by amagico** [comment]
to be specific, we use WinForms...

**Comment by Smurf-IV** [comment]
Nearly there:
![image](https://user-images.githubusercontent.com/2418812/56092950-dc08c100-5eba-11e9-9322-47515a6be646.png)

**Comment by amagico** [comment]
nice :)
