### ISSUE TITLE
Krypton Toolkit Components Designer Editors do not work in VisualStudio 2019

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-5.470#123]
- Open an existing project in Visual Studio 2019
- Open the Designer
- Select a Krypton Toolkit item (This was a 5.472 in a .Net 4.8 project !)
- Try and click a drop down item to allow editing
..... Nothing !
![image](https://user-images.githubusercontent.com/2418812/55724424-46c18480-5a03-11e9-9c4a-baa759829f46.png)

**Comment by Smurf-IV** [comment]
Opening the same project in Studio 2017, then the designers **work**.

**Comment by Wagnerp** [comment]
It might be a bug with the IDE itself.

**Comment by Smurf-IV** [comment]
> 
> 
> It might be a bug with the IDE itself.

Agreed

**Comment by Smurf-IV** [comment]
Start a new Test `WinForm Project` in Vis 2019 as .net 4.8
Loaded via Nuget the latest `Krypton 4.8`
Added a `KButton` onto the raw form (i.e. `WinForm` not `KryptonForm`)
Designer works as expected!
Got to move on with something else now...
