### ISSUE TITLE
Super Tool Tips flashes 

### ISSUE THREAD

**Issue by SuperDaveOsbourne** [Wagnerp/Krypton-NET-5.470#127]
I am upgrading from the last commercial release and the only issue is that the tooltip hover just flashes for my super tooltips.  Doesnt seem to matter what I set the Automatic Delay AutoPopDelay ReshowDelay. Just flashes the correct text and then reflashes for a tenth of a second every second. 

Any pointers to what has or could have changed during those updates? Maybe where to look?

**Comment by Wagnerp** [comment]
@Smurf-IV 

The issue might be that I need to update the `5.472` & `5.480` NuGet packages. Bit busy setting up my VS 2019 dev environment to do this.

**Comment by SuperDaveOsbourne** [comment]
KryptonToolkitSsuite5472 on .net 4.7.2.  Tried it both in VS 2019 and 2017 just in case. Same behavior.

**Comment by Smurf-IV** [comment]
This is what the "Normal" tooltip from winforms does when the mouse becomes part of the Tooltip window (i.e. it it is over the tooltip) use an offset position to inform the tooltip where to locate when it pops-up.
Microsoft now about this, that is why they have changed the behavior in some of their recent apps (And in .net 4.8) to tkae the mouse position out of the equation when a tool tip pops up under th mouse.

**Comment by SuperDaveOsbourne** [comment]
Ok I am confused. What is the resolution to this issue? It won't be fixed it will, or has already been.

**Comment by Smurf-IV** [comment]
@SuperDaveOsbourne Try the Placement mode to see if this fixes your issue.

**Comment by SuperDaveOsbourne** [comment]
I did and where you can use it, it does. A lot of the other ribbon items not so. Was still looking up the food chain to see if I could set it on the tooltip control or somewhere else. Would be nice to see a global setting where all would inherit as the default.

**Comment by Smurf-IV** [comment]
So which setting is "Good" and which is bad ?
I can then change the default.

**Comment by SuperDaveOsbourne** [comment]
The ones that I changed to MousePoint seemed to work. But like I said, not many of the controls in my application have that option in the ribbon. Won't really get to spend time with it for another 5 hours and I get home.

**Comment by Wagnerp** [comment]
Hi @SuperDaveOsbourne 

I have updated the NuGet package of `5.472` to build 856 today. That was the last release I uploaded 5 days ago.

**Comment by SuperDaveOsbourne** [comment]
Didn't seem to change anything in the ribbon controls. 5.472.856.0

**Comment by Wagnerp** [comment]
Hi @SuperDaveOsbourne 

Is it all of or just some of the controls?

**Comment by SuperDaveOsbourne** [comment]
Just some

**Comment by Wagnerp** [comment]
Could you list them please?

**Comment by SuperDaveOsbourne** [comment]
Yes, I will do a new project to so I can see whats going on that I can share. Going to be later tonight in the US.

**Comment by Wagnerp** [comment]
That's ok, I'll have a look tomorrow, as we're on BST/GMT time here.

**Comment by SuperDaveOsbourne** [comment]
Is there a way to PM you a link to my project at dropbox? You can email me at DW.Volume@gmail.com.

**Comment by Wagnerp** [comment]
Hi @SuperDaveOsbourne 

I've sent you an e-mail, so you can send me a link.

**Comment by SuperDaveOsbourne** [comment]
Done

**Comment by Wagnerp** [comment]
Yes, I see what you mean. @Smurf-IV Is there a way that I can send it over to you?

**Comment by Wagnerp** [comment]
Yes, I see what you mean. @Smurf-IV Is there a way that I can send it over to you?

**Comment by Wagnerp** [comment]
Weirdly, it seems to do it **if** you have multiple lines of text

**Comment by Wagnerp** [comment]
Is there a maximum image size that you can have, as it seems to do it with large images? @SuperDaveOsbourne can you try resizing your images to either 64 x 64 or 32 x 32 and see if it still persists?

**Comment by Smurf-IV** [comment]
I accidentally used an image that was 400x400 px, thinking it would resize to a thumbnail.. It doesn't do the resize!
Also in the Elucidate project, I have a Tooltip that fills the entire height of the screen, again from a resource string, and by accident.

**Comment by SuperDaveOsbourne** [comment]
Don't think its that, it does it on the check boxes with no images too.

**Comment by SuperDaveOsbourne** [comment]
I think you are right about the multiple lines.

**Comment by Wagnerp** [comment]
It doesn't do it with one line text. umm...

**Comment by Smurf-IV** [comment]
![image](https://user-images.githubusercontent.com/2418812/55977039-b9419700-5c85-11e9-99c8-af305fa65947.png)

**Comment by Wagnerp** [comment]
One thing I don't understand is it doesn't do it if your pointer is in a specific position????????

**Comment by Smurf-IV** [comment]
> 
> 
> Yes, I see what you mean. @Smurf-IV Is there a way that I can send it over to you?

Did you get my email ?

**Comment by Wagnerp** [comment]
Yes, I've sent over the link. It seems to be on a timer.

**Comment by Wagnerp** [comment]
Just a thought, could they be tied to a timer?

**Comment by Wagnerp** [comment]
@SuperDaveOsbourne 

There may also be another issue in your app. To use side panels, you need to use the `KryptonDockableNavigator` to get the desired behaviour, otherwise upon hiding the panel, you'll be left with white space.

**Comment by Smurf-IV** [comment]
> 
> 
> Just a thought, could they be tied to a timer?

They are, that's why there is a delay to show, and a "small" delay to hide, thus causing the flashing.
I have a fix, Just testing now !

**Comment by SuperDaveOsbourne** [comment]
Thanks, I was doing something in the code to handle that, but will go back and fix it.

**Comment by Smurf-IV** [comment]
@SuperDaveOsbourne Is this what the older version used to do ?
![image](https://user-images.githubusercontent.com/2418812/55980400-4ee02500-5c8c-11e9-8421-eb990ffb1694.png)

As in, the tooltip was always offset below the Tab bar ?

**Comment by Wagnerp** [comment]
@Smurf-IV and @SuperDaveOsbourne 

Having it offset would make more sense, as it could engulf the button

**Comment by Smurf-IV** [comment]
I could change the offset, so that it is half-way along the bottom region.
It cannot be in the "Button" region, as that mouse pointer could be "Just" inside, thus back to the flashing.
This is caused by the TabGroup having "Special" tooltip control, which is then routed through to the Krypton Tooltip.
Another way is to change the routing so that it is always uses an offset from the mouse, but if the tooltip tries to display off a right screen edge, then it will bounce back into the mouse pointer causing flashing again.
Or even this as a default:
![image](https://user-images.githubusercontent.com/2418812/55981359-5dc7d700-5c8e-11e9-91b7-ff361dc0e859.png)

**Comment by SuperDaveOsbourne** [comment]
Emailed  a YouTube link showing them in the past...

**Comment by Smurf-IV** [comment]
> 
> 
> Emailed a YouTube link showing them in the past...

Not to me :-(

**Comment by SuperDaveOsbourne** [comment]
https://www.youtube.com/watch?time_continue=58&v=lajMgp4tewA   46 seconds in...

**Comment by Smurf-IV** [comment]
Cheers, then the option for as close as possible will be better all round.
I'll do it this weekend ..

**Comment by Smurf-IV** [comment]
I'll be delivery this:
![image](https://user-images.githubusercontent.com/2418812/56076349-f31ab680-5dc7-11e9-9003-45d7c72f3092.png)

**Comment by SuperDaveOsbourne** [comment]
The new fix deletes some tabs in the ribbon and removes the text on the tab itself in the project I sent you.. 5.472.890

**Comment by Wagnerp** [comment]
Hi @SuperDaveOsbourne 

See issue #142 for details
