### ISSUE TITLE
Projects ending in 2018 can be deleted ?

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-5.470#130]
These are still littered around the codebase 
e.g. 
![image](https://user-images.githubusercontent.com/2418812/55884103-62fa2880-5b9f-11e9-836f-ee53520061c7.png)

**Comment by Wagnerp** [comment]
Yes, I don't know why they weren't renamed when I updated the year.

**Comment by Smurf-IV** [comment]
@Wagnerp "Old" projects removed, I'll now go through and remove the nuget references, so that the demo projects use the current "developer" bin references

**Comment by Smurf-IV** [comment]
Demo projects still have the 2018 projects, in the source tree.
