### ISSUE TITLE
Was the `OnDropDownClosed()` event dropped from `KryptonComboBox`?

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-NET-5.470#132]
Upon updating the toolkit suite for the extended version, I noticed that was no longer valid.

`protected override void OnDropDownClosed(EventArgs e)`

**Comment by Smurf-IV** [comment]
**This** is still there .....
```C#
        /// <summary>
        /// Indicates that the drop-down portion of the KryptonComboBox has closed.
        /// </summary>
        [Description("Indicates that the drop-down portion of the KryptonComboBox has closed.")]
        [Category("Behavior")]
        public event EventHandler DropDownClosed;
```

which is then redirected via 
`             protected void OnDropDownClosed(EventArgs e) => DropDownClosed?.Invoke(this, e);`

Argh..

I see what has happened... the `virtual` has been removed from this callback redirectors.. It was ReSharper having _fun_!
