### ISSUE TITLE
Ribbon tab text and window title text is black and bold

### ISSUE THREAD

**Issue by DarthVader85PA** [Wagnerp/Krypton-NET-5.470#135]
In Version (Build 794) is the ribbon tab text and window title text black and bold. This doesn't fit together.

![grafik](https://user-images.githubusercontent.com/32876506/55910229-30235500-5bde-11e9-88e2-b2b659f103bb.png)

On mouse over on a non selected tab the title-text is normal.

**Comment by Smurf-IV** [comment]
@DarthVader85PA 

1. Does this also happen in the Demo application if you change the style of the font ?
2. What Pallette was currently in use?
3. What OS are you running it on ?
4. What theme is currently active on that OS ?

**Comment by Smurf-IV** [comment]
Please check with the latest (901) as this might be fixed via #142
