### ISSUE TITLE
STAThread missing when open a dialog in BackgroundWorker

### ISSUE THREAD

**Issue by DarthVader85PA** [Wagnerp/Krypton-NET-5.470#136]
In the latest version (Build 856) of the NuGet-Package i get an error that the STAThreadAttribute is missing when I open a KryptonForm in a BackgroundWorker-Run-Method. In the build before the dialog will open normally.

**Comment by Smurf-IV** [comment]
[https://stackoverflow.com/questions/6373645/**c-sharp-winforms-how-to-set-main-function-stathreadattribute**]("https://stackoverflow.com/questions/6373645/c-sharp-winforms-how-to-set-main-function-stathreadattribute)"

**Comment by Smurf-IV** [comment]
The Above, Or I could fix it, so that the STAThread _Law_ that was being broken can _remain_ broken. but this can lead to rather painful debugging when trying to find what may have gone wrong ?

**Comment by Wagnerp** [comment]
Hi @Smurf-IV 

I think that it would be better adding it to a `troubbleshooting` section in the help file.
