### ISSUE TITLE
nuget tags need to be more extensive / descriptive

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-5.470#137]
The existing nuget Tags:
![image](https://user-images.githubusercontent.com/2418812/56076230-7cc98480-5dc6-11e9-8233-97cd1f5d6025.png)

Should be extended to include 
Controls, DataGrid, Ribbon, Workspace, Tabs, .Net, Docking
So that searches can have a better hit return on this work :-)

**Comment by Wagnerp** [comment]
Will do on the next release. Probaly tomorrow, been enhancing the `ExceptionHandler` class, so I can implement a proper bug reporting framework to use in apps.

**Comment by Smurf-IV** [comment]
I just use `ExceptionLess` for FOSS projects, it integrates with `NLog` properly.

**Comment by Wagnerp** [comment]
I was kind of thinking developing a front end, so that users can submit bug reports back to the developer when a app crashes, using the Krypton toolkit as the UI?

**Comment by Smurf-IV** [comment]
This is what I have done (4 times for different companies) via Krypton controls
![image](https://user-images.githubusercontent.com/2418812/56077297-6a554800-5dd2-11e9-886c-313e9aba7e85.png)

**Comment by Wagnerp** [comment]
Yes that's what I'm thinking of, then sending the reports off to the developer (of course they will need to configure it to suit their needs, i.e e-mail)
