### ISSUE TITLE
Missing text in ribbon tab

### ISSUE THREAD

**Issue by Tape-Worm** [Wagnerp/Krypton-NET-5.470#142]
Upgraded to 890 (latest as of this writing) this morning.

Ran my application and got this:
![image](https://user-images.githubusercontent.com/9710137/56095854-1a43b780-5e9e-11e9-916b-fa0855b049b4.png)

This is what I should be seeing (and did until I upgraded):
![image](https://user-images.githubusercontent.com/9710137/56095920-cd141580-5e9e-11e9-8735-9d18d5d38ae3.png)

This also fails to render in the designer as well.

I checked the Text property for the tab, it is set correctly, no code has been altered since upgrading.

Also, I tried changing the foreground color of the tab, and nothing happened.  So, I changed the background colors of the tab and got this:
![image](https://user-images.githubusercontent.com/9710137/56096126-50366b00-5ea1-11e9-86b1-9f277c29186d.png)

As you can see, there's no text at all.  Am I missing something?  Did I not set a property correctly?  Is this a rendering bug?

Just for reference: My palette is based Office 365 - Black 

I've also reproduced this in build 872 as well, downgrading to build 856 fixed the problem.  I also tried the .NET 4.7.2 version of these components, and they exhibit the same behavior.

I'm currently running Windows 10 (Version 10.0.17763.437), and using Visual Studio 2019.  As I said before, everything was rendering fine until I upgraded to build 890.

**Comment by Tape-Worm** [comment]
Just FYI, I'm able to reproduce this issue in your example Application Menu example:
![image](https://user-images.githubusercontent.com/9710137/56096192-1154e500-5ea2-11e9-965d-df20b8f602f9.png)

**Comment by Tape-Worm** [comment]
So, for giggles, I've been digging through the code and it appears that the native call to DrawThemeTextEx is not actually drawing anything.  I'm currently trying to see why that might be.

**Comment by Tape-Worm** [comment]
OK, I managed to find out what the problem was, and how to fix it.

Somewhere along the way, you guys had this in the DrawCompositionText in the AccurateText.cs file:
`IntPtr hDIB = PI.CreateDIBSection(gDC, bmi, 0, 0, IntPtr.Zero, 0);`

And then it got changed to this:
`IntPtr hDIB = PI.CreateDIBSection(gDC, ref bmi, 0, out _, IntPtr.Zero, 0);`

By adding the pass-by-reference keyword, things stopped working.  And removing the by-ref fixed the issue.  

Why?  Well, you're passing a reference type, not a value type for the _bmi_ parameter.  So, basically, by passing a reference type byref, you're essentially passing a double pointer (BITMAPINFO **pBmi instead of BITMAPINFO *pBmi).  CreateDIBSection just requires a single pointer to the bitmap info structure.

Converting the PBITMAPINFO into a class from a struct solved the issue nicely.

When accessing native code, you really should be using structs to do the data passing.  They're really built for that purpose.  Passing reference types usually involves a fair bit of marshaling overhead, which you kinda want to avoid for performance reasons, if not for just general weirdness that'll pop up.

**Comment by Tape-Worm** [comment]
I've corrected the issue and submitted a PR (#143) to incorporate it in your next release (which hopefully will be soon, this is a pretty bad bug).

**Comment by Smurf-IV** [comment]
That should be easy to chnage back,
but
https://www.pinvoke.net/default.aspx/gdi32/CreateDIBSection.html

States it should be an `[in] ref` which is why I changed it..

Here is code that uses it that way
http://www.wischik.com/lu/programmer/1bpp.html

So perhaps it is being "Misused currently"

**Comment by Tape-Worm** [comment]
Yes, that's right because it expects BITMAPINFO to be a struct, it was a class. Your signature is fine, it's the BITMAPINFO declaration that's wrong.

**Comment by Smurf-IV** [comment]
Just had a quick look and a lot of the other "types" in there are of mixed format as well.
e.g. `MONITORINFO`
Needs a good tidy-up and review of usages.

Also why is this `PI` class repeated separately in Ribbon ??
Should be at least a "friend" !

**Comment by Tape-Worm** [comment]
Good question, I noticed that too.  Really should have a single source of truth for those methods.  

After I converted BITMAPINFO to use struct, I only counted 2... maybe 3 class types in the PInvoke class.  One (POINTC) looks like it's legitimately being used as a ref type, so changing that might break stuff.

**Comment by Wagnerp** [comment]
I'll upload new packages today
