### ISSUE TITLE
ShadowBox Shown in IDE Designer is inthe wrong place...

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-NET-5.470#145]
Does anyone else have this issue?

![image](https://user-images.githubusercontent.com/949607/56113159-f2635b00-5f54-11e9-8eb4-68edc6db7bc1.png)

**Comment by Smurf-IV** [comment]
Yes, 
It is from the designer when you enable the shadows and then re-open,
I thought it was useful to give an indication of the "Area" that would be occupied.
I have my IDE on the Left monitor so it looked better.
I can investigate how to disable it

**Comment by Wagnerp** [comment]
Ahh... sorry I didn't know. Makes sense now, I'll put it in the changelog.

**Comment by Smurf-IV** [comment]
@Wagnerp Is this still a thing with the latest code and IDE, I do not seem to get it anymore since the re-write of Shadows ...

**Comment by Wagnerp** [comment]
@Smurf-IV I'll check it out ASAP (probably be Monday)

**Comment by Wagnerp** [comment]
Hi @Smurf-IV 

The issue seems to be fixed.
