### ISSUE TITLE
License Demo and installer still exist in the code base

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-5.470#148]
Are these used anywhere now ?

Krypton-NET-5.470/Source/Krypton Components/ComponentFactory.Krypton.Navigator/

![image](https://user-images.githubusercontent.com/2418812/56151602-84954e80-5fa9-11e9-9258-8c711e777090.png)

and what about these?

![image](https://user-images.githubusercontent.com/2418812/56151639-97a81e80-5fa9-11e9-979c-6157f0830759.png)

**Comment by Wagnerp** [comment]
No, they can be removed

**Comment by Smurf-IV** [comment]
I was running it from a remote drive, therefore when the UAC was supposed to pop-up, it just bombed out as above.
The installer should either copy local, or state up front that UAC is needed (i.e. use a manifest to make user copy to local machine) via an icon overlay in Explorer (Automatic via manifest)

**Comment by Wagnerp** [comment]
Might need to look for an alternative installer, would WIX work? Or I could try NSIS?

**Comment by Wagnerp** [comment]
Maybe with this theme?

![image](https://user-images.githubusercontent.com/949607/56235312-1ae77400-607f-11e9-9475-d9a6e724708d.png)

**Comment by Smurf-IV** [comment]
I use WIX all the time,
As I understand it: Nullsoft would be easier for something like this, because its a "Take directory" and install it with a shortcut to 1 app
