### ISSUE TITLE
[Bug] Adding a ribbon control to a blank form causes the form title bar to always be blue (system accent) when selected

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-NET-5.470#162]
As reported originally by @SuperDaveOsbourne [here](https://github.com/ComponentFactory/Krypton/issues/179)

![image](https://user-images.githubusercontent.com/949607/56605023-1977f780-65fb-11e9-83c4-a92f5b129ad8.png)

![image](https://user-images.githubusercontent.com/949607/56605120-4cba8680-65fb-11e9-9237-3011dc22e689.png)

5.472.720.0

Create a windows form
Nuget KryptonExtendedToolkit5472 or KryptonToolkitSuite5472
Add : KryptonForm to the form class.
Include using ComponentFactory.Krypton.Toolkit;

Add a ribbon control.

Set the Palettemode to Office 365 black on both the form and the ribbon. The form title bar is always blue when the form is selected.

Shows correctly in the designer, or at least as I think it should.

If you use a KryptonPalette and hook them up to it, behavior is the same.

Extended and regular packages the same.

Only shows correct colors when not selected.

**Comment by Wagnerp** [comment]
I don't know if we can specify a single window accent colour without changing the system global settings?

**Comment by Wagnerp** [comment]
https://www.codeproject.com/Questions/495980/Howplustopluschangeplusthepluscolorplusofplusthepl

**Comment by Wagnerp** [comment]
https://www.c-sharpcorner.com/forums/windows-form-title-bar-colour

**Comment by Smurf-IV** [comment]
I do not think it is a problem with the Office 365: From the Ribbon Demo App:
![image](https://user-images.githubusercontent.com/2418812/56791171-519b5800-67fe-11e9-84d5-f00f435fa2df.png)

**Comment by SuperDaveOsbourne** [comment]
If you follow my procedure, do you get the same results? Maybe something in the designer or maybe something I am doing wrong?

**Comment by Smurf-IV** [comment]
Even with the `Ribbon Demo App` the designer shows it working, but when run, it does not do "Chrome painting"!
Trying to get to the bottom of this.

**Comment by SuperDaveOsbourne** [comment]
![image](https://user-images.githubusercontent.com/4176416/56806821-06337a80-67fb-11e9-8118-e36e832e1a1f.png)

Is what I am testing on.

**Comment by Smurf-IV** [comment]
Related: 
https://github.com/ComponentFactory/Krypton/issues/42
https://github.com/Wagnerp/Krypton-NET-5.470/issues/68

**Comment by SuperDaveOsbourne** [comment]
AllowFormIntegrate = false : Behavior the same.

**Comment by Smurf-IV** [comment]
@SuperDaveOsbourne Agreed, the related, where to show that this is not a **new** problem; and was for me to then clear them up if I found a solution.

In the meantime, If you run the "Memo Editor" example from the `Workspace Examples` solution, then it shows that with the existing code it is possible.

What I have to do now, is find out **_how_** that is working !

**Comment by Smurf-IV** [comment]
@SuperDaveOsbourne I have found the workaround. I'll do a fix for it soon..
Workaround:
In the Form, 
After `InitializeComponent();`
you have to "**Force**" `kryptonRibbon1.AllowFormIntegrate = false;`

**Comment by SuperDaveOsbourne** [comment]
Yes that does work. Put it right before the resume layout calls. Don't know if it matters where...

**Comment by Wagnerp** [comment]
@SuperDaveOsbourne 

I'll publish a new NuGet package ASAP

**Comment by SuperDaveOsbourne** [comment]
Spoke to soon, now the ribbon buttons are blue... Will see if it is something on my side.

**Comment by Smurf-IV** [comment]
The Ribbon Application Menu Test application works as expected for the themes it has, Are you using one of the newer themes ?
![image](https://user-images.githubusercontent.com/2418812/56846156-668def00-68c3-11e9-840d-b70da0ead797.png)

**Comment by SuperDaveOsbourne** [comment]
Tried all themes.

![image](https://user-images.githubusercontent.com/4176416/56847881-b19e0700-68af-11e9-9401-c936c6b57747.png)



namespace WindowsFormsApp3
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            ComponentFactory.Krypton.Toolkit.Values.PopupPositionValues popupPositionValues1 = new ComponentFactory.Krypton.Toolkit.Values.PopupPositionValues();
            this.kryptonRibbon1 = new ComponentFactory.Krypton.Ribbon.KryptonRibbon();
            this.kryptonRibbonQATButton1 = new ComponentFactory.Krypton.Ribbon.KryptonRibbonQATButton();
            this.kryptonRibbonQATButton2 = new ComponentFactory.Krypton.Ribbon.KryptonRibbonQATButton();
            this.kryptonRibbonQATButton3 = new ComponentFactory.Krypton.Ribbon.KryptonRibbonQATButton();
            this.kryptonRibbonTab1 = new ComponentFactory.Krypton.Ribbon.KryptonRibbonTab();
            this.kryptonRibbonGroup1 = new ComponentFactory.Krypton.Ribbon.KryptonRibbonGroup();
            this.kryptonRibbonGroupTriple1 = new ComponentFactory.Krypton.Ribbon.KryptonRibbonGroupTriple();
            this.kryptonRibbonGroupButton1 = new ComponentFactory.Krypton.Ribbon.KryptonRibbonGroupButton();
            ((System.ComponentModel.ISupportInitialize)(this.kryptonRibbon1)).BeginInit();
            this.SuspendLayout();
            // 
            // kryptonRibbon1
            // 
            this.kryptonRibbon1.InDesignHelperMode = true;
            this.kryptonRibbon1.Name = "kryptonRibbon1";
            this.kryptonRibbon1.PaletteMode = ComponentFactory.Krypton.Toolkit.PaletteMode.Office2007Black;
            this.kryptonRibbon1.QATButtons.AddRange(new System.ComponentModel.Component[] {
            this.kryptonRibbonQATButton1,
            this.kryptonRibbonQATButton2,
            this.kryptonRibbonQATButton3});
            this.kryptonRibbon1.RibbonTabs.AddRange(new ComponentFactory.Krypton.Ribbon.KryptonRibbonTab[] {
            this.kryptonRibbonTab1});
            this.kryptonRibbon1.SelectedTab = this.kryptonRibbonTab1;
            this.kryptonRibbon1.Size = new System.Drawing.Size(800, 115);
            this.kryptonRibbon1.TabIndex = 0;
            popupPositionValues1.PlacementMode = ComponentFactory.Krypton.Toolkit.PlacementMode.Bottom;
            this.kryptonRibbon1.ToolTipValues.ToolTipPosition = popupPositionValues1;
            // 
            // kryptonRibbonTab1
            // 
            this.kryptonRibbonTab1.Groups.AddRange(new ComponentFactory.Krypton.Ribbon.KryptonRibbonGroup[] {
            this.kryptonRibbonGroup1});
            // 
            // kryptonRibbonGroup1
            // 
            this.kryptonRibbonGroup1.Items.AddRange(new ComponentFactory.Krypton.Ribbon.KryptonRibbonGroupContainer[] {
            this.kryptonRibbonGroupTriple1});
            this.kryptonRibbonGroup1.DialogBoxLauncherClick += new System.EventHandler(this.kryptonRibbonGroup1_DialogBoxLauncherClick);
            // 
            // kryptonRibbonGroupTriple1
            // 
            this.kryptonRibbonGroupTriple1.Items.AddRange(new ComponentFactory.Krypton.Ribbon.KryptonRibbonGroupItem[] {
            this.kryptonRibbonGroupButton1});
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.kryptonRibbon1);
            this.Name = "Form1";
            this.kryptonRibbon1.AllowFormIntegrate = false;
            this.PaletteMode = ComponentFactory.Krypton.Toolkit.PaletteMode.Office2007Black;
            this.Text = "Form1";
            ((System.ComponentModel.ISupportInitialize)(this.kryptonRibbon1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private ComponentFactory.Krypton.Ribbon.KryptonRibbon kryptonRibbon1;
        private ComponentFactory.Krypton.Ribbon.KryptonRibbonTab kryptonRibbonTab1;
        private ComponentFactory.Krypton.Ribbon.KryptonRibbonGroup kryptonRibbonGroup1;
        private ComponentFactory.Krypton.Ribbon.KryptonRibbonQATButton kryptonRibbonQATButton1;
        private ComponentFactory.Krypton.Ribbon.KryptonRibbonQATButton kryptonRibbonQATButton2;
        private ComponentFactory.Krypton.Ribbon.KryptonRibbonQATButton kryptonRibbonQATButton3;
        private ComponentFactory.Krypton.Ribbon.KryptonRibbonGroupTriple kryptonRibbonGroupTriple1;
        private ComponentFactory.Krypton.Ribbon.KryptonRibbonGroupButton kryptonRibbonGroupButton1;
    }
}

**Comment by Wagnerp** [comment]
Hi @SuperDaveOsbourne 

I will update the package later today

**Comment by Smurf-IV** [comment]
You have overridden the global palette !
`this.kryptonRibbon1.PaletteMode = ComponentFactory.Krypton.Toolkit.PaletteMode.Office2007Black;`

So if I set it to white in the Demo app I get this regardless of the the Global Theme chosen:

![image](https://user-images.githubusercontent.com/2418812/56848359-f5a90000-68df-11e9-95a8-7dfdb29d2572.png)

**Comment by SuperDaveOsbourne** [comment]
Ok, seems like creeped in when I was trying everything to get the form to corporate.  Sounds like we are good to go.
