### ISSUE TITLE
Can not hide checkboxes for nodes in KryptonTreeView

### ISSUE THREAD

**Issue by mace17** [Wagnerp/Krypton-NET-5.470#176]
After changing a regular TreeView to a KryptonTreeView, hiding check boxes for nodes does not work.
This is code that I use http://dotnetfollower.com/wordpress/2011/05/winforms-treeview-hide-checkbox-of-treenode/.

Does anyone have idea why this does not work?

**Comment by Smurf-IV** [comment]
I have found the reason...
from inside the Krypton code it does this ->
```C#
// If showing check boxes then used fixed entries from the state image list
if (CheckBoxes)
{
    drawStateImage = e.Node.Checked ? StateImageList.Images[1] : StateImageList.Images[0];
}
etc.
```
Meaning, that it _Always_ draws the checkbox,  if the TreeView has it turned on, regardless of the node state value.

**Comment by Smurf-IV** [comment]
The Following code will need an updated Krypton Components (Or build directly)
It will include an updated KryptonTreeView Example:
![image](https://user-images.githubusercontent.com/2418812/57969040-f62a3900-7969-11e9-85df-19f102efb2b1.png)

Code to toggle the CheckBox Visibility
```C#
private void BtnToggleNodeCheckBox_Click(object sender, EventArgs e)
{
    if (kryptonTreeView.SelectedNode is KryptonTreeNode kryptonNode)
    {
        kryptonNode.IsCheckBoxVisible = !kryptonNode.IsCheckBoxVisible;
    }
}
```

And (Optional) add an event handler on the treeview to do this:
```C#
private void KryptonTreeView_BeforeCheck(object sender, TreeViewCancelEventArgs e)
{
    if (kryptonTreeView.SelectedNode is KryptonTreeNode kryptonNode)
    {
        // If the CheckBox is hidden then prevent the checking change event
        e.Cancel = !kryptonNode.IsCheckBoxVisible;
    }
}
```
