### ISSUE TITLE
[BUG] Control in Krypton Ribbon Properties binding is not working

### ISSUE THREAD

**Issue by minhphuong0401** [Wagnerp/Krypton-NET-5.470#177]
**Describe the bug
Properties binding is not working for all control in Ribbon

**To Reproduce**
1. Drag Krypton Ribbon to any new form
2. Create new tab and new group
3. Add a checkbox to the group
4. Bind Checked properties of the checkbox to a variable in Settings
5. Setup Form Closing event to save the settings
6. Run the form, change the checked state of the checkbox (true to false or false to true), close the form

**Expected behavior**
When open the form again, the Checked value of Checkbox should be the same as the variable in Settings

**Comment by Smurf-IV** [comment]
It turns out that "None" of the `Krypton Ribbon bindable properties` work !

**Comment by Smurf-IV** [comment]
@minhphuong0401 you will need to get the latest code, and then remove and then re-add the `PropertyBinding` so that the designer then fills in the correct `(DataBindings)` section:
![image](https://user-images.githubusercontent.com/2418812/59147165-2a849880-89f0-11e9-811b-fab8a56a91f3.png)
