### ISSUE TITLE
AppVeyor builds are not working

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-5.470#180]
Users cannot "Get" the latest because the output build from AppVeyor does not work:

https://ci.appveyor.com/project/Wagnerp/krypton-net-5-470/history

**Comment by Wagnerp** [comment]
Is AppVeyor for unit testing, if so I'll try to disable it.

**Comment by Smurf-IV** [comment]
It should be for performing builds, and then the artifacts can be downloaded by those who want cutting edge builds,
It has probably not been set up for .Net, I've never used for this type of project, but other have got it working within GitHub to produce .Net projects.

**Comment by Wagnerp** [comment]
I'll have a look into it.

**Comment by Wagnerp** [comment]
Hi @Smurf-IV 

I've removed AppVeyor from the builds.
