### ISSUE TITLE
Adding/Removing Ribbon tabs can cause NullReferenceException

### ISSUE THREAD

**Issue by jpatte** [Wagnerp/Krypton-NET-5.470#185]
Hello,

We have an app that dynamically adds and removes ribbon tabs depending on the context. We have observed that a NullReferenceException in `ViewDrawRibbonGroupsBorderSynch` may cause the app to crash occasionally. 

The problem is in ComponentFactory.Krypton.Ribbon\View Draw\ViewDrawRibbonGroupsBorderSynch.cs, line 72: the code checks if `Ribbon.SelectedTab` isn't `null` but, unlike all the other methods in the same source file, it omits to check if `_tabToView` has an entry for this tab. Simply adding this check fixes the issue.

I would gladly submit a pull request to fix this but I'm not sure which repository is used to maintain the source code.

Could you make this change?
Thanks!

Julien

**Comment by Wagnerp** [comment]
Hi @jpatte 

Thank you for the message, this is the correct repository to pull requests to fix any issues that you find, as this is used for every other published version.

**Comment by Wagnerp** [comment]
Hi @jpatte 

Is this what you mean?

```C#
 public ViewDrawRibbonGroup ViewGroupFromPoint(Point pt)
        {
            // There can only be groups showing for the currently selected tab
            if (Ribbon.SelectedTab != null && _tabToView != null)
            {
                // Get the scroll port for this tab
                ViewLayoutRibbonScrollPort viewScrollPort = _tabToView[Ribbon.SelectedTab];

                // The first child of the scroll port is always the view control
                ViewLayoutControl viewControl = viewScrollPort[0] as ViewLayoutControl;

                // The first child of the view control is always the ribbon groups
                ViewLayoutRibbonGroups viewGroups = viewControl.ChildView as ViewLayoutRibbonGroups;

                // Ask the view groups to find a matching group
                return viewGroups.ViewGroupFromPoint(pt);
            }

            return null;
        }
```

**Comment by jpatte** [comment]
Hi, actually what I mean is:

```csharp
public ViewDrawRibbonGroup ViewGroupFromPoint(Point pt)
        {
            // There can only be groups showing for the currently selected tab
            if((Ribbon.SelectedTab != null) &&
               (_tabToView.ContainsKey(Ribbon.SelectedTab)))
            {
                // Get the scroll port for this tab
                ViewLayoutRibbonScrollPort viewScrollPort = _tabToView[Ribbon.SelectedTab];

                // The first child of the scroll port is always the view control
                ViewLayoutControl viewControl = viewScrollPort[0] as ViewLayoutControl;

                // The first child of the view control is always the ribbon groups
                ViewLayoutRibbonGroups viewGroups = viewControl.ChildView as ViewLayoutRibbonGroups;

                // Ask the view groups to find a matching group
                return viewGroups.ViewGroupFromPoint(pt);
            }

            return null;
        }
```

We need to check if `_tabToView` contains an entry for `Ribbon.SelectedTab` otherwise `_tabToView[Ribbon.SelectedTab]` could throw an exception. That same check is already done in all the other methods of this class.

Thanks for letting me know about the repo, I'll submit pull requests if I stumble upon any other issue.

**Comment by Wagnerp** [comment]
Just added the fix, it'll be included in the next update.

**Comment by jpatte** [comment]
Great, thanks!
