### ISSUE TITLE
[BUG] Drop Shadow appears to be red in 1903

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-NET-5.470#186]
Since upgrading from 1809 to 1903 `10.0.18362`, drop shadows appear to be red instead of grey.

![Annotation 2019-05-24 083742](https://user-images.githubusercontent.com/949607/58310832-797edb00-7dff-11e9-8098-b5d3ec330744.png)

**Comment by Wagnerp** [comment]
My mistake, change the colour value!!!!!!!!!!!!!!

**Comment by Smurf-IV** [comment]
It also looks like you had the  `Use Drop Shadow` from the old method enabled as well.
