### ISSUE TITLE
KryptonComboBox does not support "Simple Style" and throws exception in Designer

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-5.470#187]
![image](https://user-images.githubusercontent.com/2418812/58378671-9ba76300-7f8f-11e9-8e70-4712b4708c42.png)

If it does not support it, then remove the styles.
No idea what would happen if done at runtime !

**Comment by Wagnerp** [comment]
I think that it uses the standard winform styles. Is there any way to override it?

**Comment by Smurf-IV** [comment]
> 
> 
> I think that it uses the standard winform styles. Is there any way to override it?

Yes, and Yes

**Comment by Wagnerp** [comment]
On another issue, we can now depreciate `TaskDialogs` in this repo, as I requested permission to use [this](https://github.com/kpreisser/TaskDialog), and the author said yes provided that I give credit where needed.

**Comment by Smurf-IV** [comment]
> On another issue, we can now depreciate `TaskDialogs` in this repo, 

Not used them in a long time......

>as I requested permission to use [this](https://github.com/kpreisser/TaskDialog), and the author said yes provided that I give credit where needed.

Will this not need the CommandLink button from the Extended set to be brought over ?

**Comment by Wagnerp** [comment]
I think I'll use the extended version to introduce it, so there will be no crossover with controls.
