### ISSUE TITLE
KryptonContextMenu for KryptonDataGridView

### ISSUE THREAD

**Issue by DarthVader85PA** [Wagnerp/Krypton-NET-5.470#191]
Is it possible in the future to add a property for the KryptonDataGridView that provides a choice for a KryptonContextMenu, like ContextMenuStrip?

Thanks

**Comment by Wagnerp** [comment]
Hi @DarthVader85PA 

I moved the feedback to here, as the standard toolkit contains the mentioned `KryptonDataGridView`.

Thanks
