### ISSUE TITLE
NumericUpDowner needs to have the "DecimalPlaces" visible in the designer

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-5.470#199]
It's public BUT not visible in the IDE designer

    /// <summary>Gets or sets the number of decimal places to display.</summary>
    [Category("Data")]
    [Description("Indicates the number of decimal places to display.")]
    [DefaultValue(0)]
    [Browsable(false)]
    public int DecimalPlaces

**Comment by Wagnerp** [comment]
Does it  have the `{ get; set; }` to make it a property?

**Comment by Smurf-IV** [comment]
Just find the code block, I placed in the 1st comment, and remove the `[Browsable(false)]`

**Comment by Wagnerp** [comment]
Done!

**Comment by Wagnerp** [comment]
Is there any reason why the default value for `DecimalPlaces` is set to **99**?
