### ISSUE TITLE
KryptonCombobox does not have DrawMode and IntegralHeight properties

### ISSUE THREAD

**Issue by mace17** [Wagnerp/Krypton-NET-5.470#203]
KryptonComboBox does not have DrawMode property, also it would be nice if DrawItem is visible in designer.

**Comment by mace17** [comment]
Same for IntegralHeight.  
It would be really useful if you can implement these proprties.

**Comment by Smurf-IV** [comment]
#198 will sort the drawItem

**Comment by Smurf-IV** [comment]
`DrawMode` has to be hidden in order for the Krypton styling to happen, i.e. it is forced to 

    _comboBox.DrawMode = DrawMode.OwnerDrawVariable;
