### ISSUE TITLE
[Question]: DLL files 

### ISSUE THREAD

**Issue by rahulmaxi** [Wagnerp/Krypton-NET-5.470#209]
Hi,
When I installed this package with Nuget package manager in VS2013 for C# project, I couldn't find dll files added in references neither in package directory to create manual references.
Can you please help me through if I am doing something incorrect.

Thanks,
R.

**Comment by Wagnerp** [comment]
Hi @rahulmaxi 

Which package did you install, as you may need the full toolkit or to download other modules?

**Comment by rahulmaxi** [comment]
Hi @Wagnerp ,

Thanks for your response. I have installed package KryptonToolkitSuite5470 -Version 5.470.1231.
This what I have done
![image](https://user-images.githubusercontent.com/51871905/61384325-00b37100-a8ce-11e9-96c0-e0c65be51828.png)

Could you please suggest what else I am missing or should install to get it working.

Thanks,
Vikrant.

**Comment by Wagnerp** [comment]
Hi @rahulmaxi 

If it compiles correctly, then you should be able to use the toolkit as normal.

**Comment by Smurf-IV** [comment]
The Krypton components are not shoing up in the project, but you have installed them at the solution level.
What version of the .Net framework have you set your project to ? (i.e. 5.**470** requires .Net **4.70**)

**Comment by rahulmaxi** [comment]
Hi @Smurf-IV ,

Thanks for pointing out the version issue. I created another one with 4.7 but still no luck. I am still missing .dll files for it. 
I can not use KryptonForm yet. 
![image](https://user-images.githubusercontent.com/51871905/61541290-01c6d880-aa5d-11e9-874c-2bbdc0fbbf83.png)

![image](https://user-images.githubusercontent.com/51871905/61541336-14411200-aa5d-11e9-97e3-c29e2701be2a.png)

To be honest I am confused how should I install this package (Krypton-NET-5.470) via nuget to get the dll files.


Thanks,
Vikrant.

**Comment by Wagnerp** [comment]
Hi @rahulmaxi 

It looks as if you haven't put in `using ComponentFactory.Krypton.Toolkit;` yet.

**Comment by rahulmaxi** [comment]
@Wagnerp ,
_using ComponentFactory.Krypton.Toolkit;_ goes unrecognized due to missing dll files. I am expecting dll files should be added in References as soon as package is installed from nuget package manager.

**Comment by Wagnerp** [comment]
Yes they should all be in the References section. Do you have a folder named `packages`? Also, what version of Visual Studio are you using?

**Comment by rahulmaxi** [comment]
I am using VS2013. I do find folder name packages with following.

![image](https://user-images.githubusercontent.com/51871905/61576319-510d1780-aaf6-11e9-9cc9-e096296d9eb9.png)

**Comment by Wagnerp** [comment]
Hi @rahulmaxi 

It seems to be a weird VS 2013 issue, all other VS versions seem to be ok.

**Comment by rahulmaxi** [comment]
Hi @Wagnerp ,
Looks like but only with Krypton-NET-5.470. When I attempt to install Krypton-Toolkit-Suite-Extended-NET-5.470 via nuget it adds references automatically(though I did not use it in any form). When I installed log4net from nuget it also worked well adding references automatically.

**Comment by Wagnerp** [comment]
Hi @rahulmaxi 

I can upload the binaries to here if you want?

**Comment by rahulmaxi** [comment]
Hi @Wagnerp ,
Thanks for your response. I installed the Krypton.Toolkit.Suite.for.NET.4.7.exe and manually added the required DLLs.
