### ISSUE TITLE
[Question]: Upgrade Krypton Toolkit in Visual Studio Project

### ISSUE THREAD

**Issue by borismatthews** [Wagnerp/Krypton-NET-5.470#210]
I hope that asking this question here is appropriate!

I have several existing .net projects that use the 4.4 release of the Krypton Toolkit and am keen to upgrade this to the latest version on GitHub to take advantage of the bug fixes etc.

I am unclear about how to do this - I have tried changing the toolkit references in the VS project but then VS complains that all the components used are 'not defined'.

I would appreciate any advice on how to complete this upgrade.

Thanks
Andy

**Comment by Wagnerp** [comment]
Hi @borismatthews 

Are you using the original `4.4.0` release? If so, have you tried downloading the newer NuGet packages?

**Comment by borismatthews** [comment]
Hi

Thanks for responding so quickly.

Yes, I am using the original 4.4.0 from Component Factory.

I downloaded and installed version 5.470.872 from GitHub (did not use NuGet, just downloaded the exe file).

It appears that the name of the reference is different and so maybe that is why Visual Studio cannot match the references of the controls to the dll’s?

The 4.4.0 references appear as follows:
[cid:image001.png@01D53BEE.AC5B7DB0]

Then when I install the updated version
[cid:image002.png@01D53BEE.F1B71360]

Regards
Andy

**Comment by Wagnerp** [comment]
Hi @borismatthews 

What version of the .NET framework are you using?

**Comment by borismatthews** [comment]
Peter

Sorry, I was targeting 4.0, have changed to 4.7.2 and all OK now.

Also, I see that you have the “Krypton-Toolkit-Suite-Extended-NET-5.470” project, is this intended to be used in addition to the standard toolkit or in place of?

Thanks
Andy

**Comment by Wagnerp** [comment]
Hi @borismatthews 

The `Krypton-Toolkit-Suite-Extended-NET-5.470` is an additional set of controls, dialogs etc that can be used in conjunction with the standard toolkit. Glad you managed to find out what the issue was.

**Comment by borismatthews** [comment]
Hi Peter

I was hoping that the updated controls would fix an issue I have in the Visual Studio designer but unfortunately it has not.

Using VS2017 on Windows 7 machine the control spacing at design time is correct but when I upgraded to a Windows 10 machine and VS2017 the spacing around the Kypton ComboBox at design time is incorrect.

If you look at this screenshot you can see that at design time the combo boxes have additional space but when you run this it appears correct – clearly not easy to layout the controls to allow for this.

Is this an issue that you are aware of and any ideas if it can be rectified?

[cid:image001.png@01D53C8A.FB06D4E0]

Thanks
Andy

**Comment by Wagnerp** [comment]
Hi @borismatthews 

Unfortunately, the screenshots don't appear. I would suggest opening a bug report detailing the problem that you have with the padding.

**Comment by Wagnerp** [comment]
Hi @borismatthews 

Can this now be closed?

**Comment by borismatthews** [comment]
Hi

Yes, that’s fine.

Thanks

**Comment by Wagnerp** [comment]
Hi @borismatthews 

Thanks, if you have anymore questions in the future, please post them to this repo.
