### ISSUE TITLE
[Question] How to set focus in KryptonTextbox that is within a KryptonPanel that is within a KryptonNavigator?

### ISSUE THREAD

**Issue by dquinter** [Wagnerp/Krypton-NET-5.470#221]
My TextBox is inside a Panel, and the Panel is inside a Navigator's page, and I can't set the focus in my TextBox when the Navigator's page is selected and shown.

Somebody can help me?

**Comment by Smurf-IV** [comment]
Can you Tab to it ? I seem to remember, that if the Krypton Component cannot be tabbed to , then it cannot be focused, due to an override in the Krypton base classes (Haven't got the code to hand)

**Comment by dquinter** [comment]
Thanks! It works
