### ISSUE TITLE
[BUG] Missing/Unreadable Ribbon Tab Text

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-NET-5.470#231]
See screen capture:

![ribbon](https://user-images.githubusercontent.com/949607/64474181-3146b700-d169-11e9-9e35-3094ec748803.png)

**Comment by Smurf-IV** [comment]
Has the above been added to an existing App within the Krypton Examples ?

**Comment by Wagnerp** [comment]
The screenshot comes from the current `Outlook Clone` example

**Comment by Wagnerp** [comment]
Found that the examples use an older version of the toolkit. Need to update the installer.
