### ISSUE TITLE
[Question]: How to Change ButtonSpecType Color ?

### ISSUE THREAD

**Issue by pc8181** [Wagnerp/Krypton-NET-5.470#233]
Krypton form i changed the StateCommon\Header backcolor to Black and add ButtonSpec in form and change it type to Pin Vertical, ButtonSpec Type icon is white in design time but in run time it will show as black color 
I'm using krypton palette 'office 365 Black',  
how to resolve this ?

Design Time :
![image](https://user-images.githubusercontent.com/13380400/65215299-b9fb1680-daca-11e9-9eac-7ffc093a6da0.png)

RunTime:
![image](https://user-images.githubusercontent.com/13380400/65215311-c1babb00-daca-11e9-96ab-fe5e505498a1.png)

**Comment by pc8181** [comment]
have any possible way to invert the form buttonspec type icon colors ?

Thanks

**Comment by Wagnerp** [comment]
Is it a custom icon?

**Comment by pc8181** [comment]
no sir this is inbuilt icon 

`  
        Friend WithEvents btnOnTop As ComponentFactory.Krypton.Toolkit.ButtonSpecAny

        Me.btnOnTop = New ComponentFactory.Krypton.Toolkit.ButtonSpecAny()
        Me.btnOnTop.Style = ComponentFactory.Krypton.Toolkit.PaletteButtonStyle.ButtonSpec
        Me.btnOnTop.Type = ComponentFactory.Krypton.Toolkit.PaletteButtonSpecStyle.PinVertical
        Me.ButtonSpecs.AddRange(New ComponentFactory.Krypton.Toolkit.ButtonSpecAny() {Me.btnOnTop})`

this icon is come from 
  

>    Me.btnOnTop.Type = ComponentFactory.Krypton.Toolkit.PaletteButtonSpecStyle.PinVertical

**Comment by Wagnerp** [comment]
Sorry I'm not familiar with `ButtonSpec`, so it may take time to investigate

**Comment by Smurf-IV** [comment]
This appears to be  2 part situation:
- Make the Office 365 Black use the white Icons ?
- Allow a way of using a different ButtonSpec Icon set ?

**Comment by Smurf-IV** [comment]
Oh, and to make things worse, there are 2 set of icons that can be used for most things, but only 1 pin type:
![image](https://user-images.githubusercontent.com/2418812/70788032-e51e9a80-1d87-11ea-83c2-ed28a978eaee.png)
These are all Buttons Specs, and using the Office2007 Black Theme. 
It's the same for the other themes.
The order is (From Left)
- Pin Vertical
- Form Min
- Workspace Max
- Form Max
- Close
- Form Close

**Comment by Smurf-IV** [comment]
It is possible to use a generic ButtonSpecType, and add your own image:
![image](https://user-images.githubusercontent.com/2418812/70788647-42671b80-1d89-11ea-8b74-763b0d7a97fb.png)

**Comment by Smurf-IV** [comment]
The Order of image retrieval:
- KryptonCommand.ImageSmall
- ImageStates
- Direct assigned Image (As in above comment)
- Inherited image
- Theme ButtonSpecImage

**Comment by Smurf-IV** [comment]
I'm setting this to "Won't fix" unless "we" want to add a new bmp to each theme and route it through for usage as a different Pin type (And the other pin type also!)
