### ISSUE TITLE
[Question]: Is there a way to remove dotted borders on OnFocus

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-NET-5.470#256]
Question from Byte: Is there a way to remove dotted borders on OnFocus?

![db1](https://user-images.githubusercontent.com/949607/71661736-10712580-2d47-11ea-98f9-a9995b4187f1.png)

**Comment by Smurf-IV** [comment]
Yes:
![image](https://user-images.githubusercontent.com/2418812/71714560-47f2d700-2e06-11ea-9f10-7695d502ca76.png)

**Comment by Wagnerp** [comment]
Will tell them
