### ISSUE TITLE
[BUG] KyptonForm fails to invalidate rendering in some situations

### ISSUE THREAD

**Issue by MGRussell** [Wagnerp/Krypton-NET-5.470#257]
When a tab is using an OpenTK GLControl inside of a KryptonDockableNavigator inside of a KryptonForm, the rendering pipeline seems to get bugged out. I suspect this is a specific example of a much more generalized issue, but this is how I hit on it and it's relatively easy to replicate.

**To Reproduce**
1. Create a project with a KryptonForm
2. Add a KryptonDockableNavigator (a basic TabControl also works) with two tabs.
3. In the first tab add a simple GLControl from [OpenTK](https://github.com/opentk/opentk). It's also available on NuGet as OpenTK.GLControl. I've included a simple snippet [here](https://gist.github.com/MGRussell/aa30d5718913e1aa2b8b22fc9ce286fa) that does nothing except create a flat colored box.
4. Run and swap between the tabs a few times. The GLControl's rendering will end up being left on the form even when swapping to the second [empty] tab. This is caused by the form not being properly invalidated as can be confirmed by forcing a redraw (such as by dragging the form off the visible screen and back).

Now change the main form to inherit from Form instead of KryptonForm. The issue disappears.

This is based on the 5.480 Krypton Build (latest commit message is "2020") and OpenTK 3.1.0.

This behavior was not present in the original Krypton toolkit.

**Comment by MGRussell** [comment]
Ok this is weird. So this bug also exists with TabControl and it exhibits the exact same behavior but, once again, only when KryptonForm and not Form is extended so there's definitely something funky going on with KryptonForm.

The weird part is is that calls to Invalidate/etc do not correct the problem. It's like the GLControl is somehow being rendered independently and 'above' the tab controls, but only when KryptonForm is used.

**Comment by MGRussell** [comment]
The bug does not exist when the form is maximized. Very interesting because the controls in my test project are not docked so the controls and everything are staying the exact same size. It's something about the form rendering that changes.

**Comment by Wagnerp** [comment]
Hi @MGRussell 

Thanks for posting your issue.

Krypton does apply its own render, so it maybe one is cancelling out the other. Do you have any examples to look at?

**Comment by MGRussell** [comment]
Couple of other interesting things. Changing the window size eliminates the glitch as well. Yet calling OnSizeChanged or SetBoundsCore had no effect. I'm not familiar enough with the Forms rendering pipeline to figure out what's being changed here, but it at least provides room for a temp work-around of just increasing/decreasing the window width by 1 one pixel when the tab is changed.

Another odd thing. This issue does not occur if the window is located on a second non-primary monitor. 

---

@Wagnerp here is a screenshot of the issue: 
![Krypton Glitch](https://user-images.githubusercontent.com/30259368/71963561-791c3e80-322e-11ea-8761-29b97784f69d.png)

What's seen there (on the first tab) is a simple GDI shaded rect. In the middle of it is the GLControl's rendering from tab page 3. I'll get a sample project uploaded.

**Comment by Wagnerp** [comment]
Is the `GLControl` in the toolbox once installed?

**Comment by MGRussell** [comment]
I've uploaded a project here: https://github.com/MGRussell/KryptonIssue

Yes - though it doesn't do anything by default. In the project I create a simple class that extends it and draws an aquamarine box.

**Comment by Wagnerp** [comment]
Is the issue that it should also appear on the `Empty` tab?

**Comment by MGRussell** [comment]
It shouldn't appear anywhere except on the third tab where it's rendered. You can see this by making the box appear on the first or second tab and then forcing a hard redraw by, for instance, dragging the program's window off the visible screen and then back.

**Comment by Wagnerp** [comment]
Please could you make a screen recording, as I don't think that I can activate the bug as described?

**Comment by MGRussell** [comment]
Oh really? So when you repeatedly swap between the third (GLControl) tab and another tab, you are not having the rendering from the GLControl's tab (the aquamarine square) appear elsewhere?

Ok, I will work on getting a screen recording made.

**Comment by MGRussell** [comment]
Video attached.

![kryptonIssue](https://user-images.githubusercontent.com/30259368/71968431-7f62e880-3237-11ea-958a-78e8ba67bdab.gif)

Demonstrated is the issue as well that resizing the window resolves it.

**Comment by Wagnerp** [comment]
That doesn't happen on my machine. What are your specs as it might be that I have more memory to play with?

**Comment by MGRussell** [comment]
Oh that's no good. It's definitely not a hardware issue. Beyond sufficient specs on my machine over here I think more important is that if you change it from a KryptonForm to a Form, the issue disappears. It also disappears with the original Krypton - but let me double check that.

**Comment by MGRussell** [comment]
Yeah, just double checked and verified - this issue is not present in the original Krypton set of controls using the package on NuGet - KryptonToolkitSuite 4.6.501.

**Comment by MGRussell** [comment]
I can also confirm that the issue is present in the KryptonToolkitSuite5470 version 5.470.700. Is there any older version on NuGet? I'd like to try to pin down where the issue occurred.

**Comment by Wagnerp** [comment]
I can bundle all the 470 nuget packages into one zip file and pass them over?

**Comment by MGRussell** [comment]
Sure, that'd be great if you could send over anything before 5.470.700 since it's also present there.

**Comment by Wagnerp** [comment]
If you go [here](https://www.nuget.org/packages/KryptonToolkitSuite5470/), they're all the nuget versions. pre 700 builds are [here](https://github.com/Wagnerp/Krypton-NET-5.470/releases) (643, 341, 633, 632, 620, 593, 572, 569, 568, 565, 562, 561, 556, 553, 524, 4.7.0)

**Comment by Wagnerp** [comment]
4.7.0 is the first ever release, dated 23rd January, 2018.

**Comment by MGRussell** [comment]
Great. Thanks a lot for the assistance here. I'll start running through those tomorrow.

I can confirm that this issue does occur on other machines as well. Just replicated it using the [release build](https://github.com/MGRussell/KryptonIssue/releases/tag/1) on another machine. Both are running Windows 7 but are otherwise completely distinct. So it may be an OS issue but is probably not a local issue.

**Comment by MGRussell** [comment]
Okay, this is good news on this bug. The 4.7.0.0 does not have the issue. But the 4.70.524 does. So the issue is related to something that happened between those two versions.

**Comment by Wagnerp** [comment]
I've ran both `KryptonNavigator` & `KryptonPage` through WinMerge, and there are no differences between them.

**Comment by MGRussell** [comment]
It's something KryptonForm or one of its bases I expect since everything works fine when the main form extends Form and not KryptonForm.

**Comment by MGRussell** [comment]
The issue is also present when using a basic TabControl instead of the KryptonNavigator.

**Comment by Wagnerp** [comment]
Still nothing.  Here is the code for both versions

[4.7.0](https://1drv.ms/u/s!AnKzT7Em-ox5g8h1_jhlgviGAalc-w?e=TsUjNp)

[4.470.524](https://1drv.ms/u/s!AnKzT7Em-ox5g8h04hTqoFtSrILpCQ?e=dkrjXk)

The issue might be in OpenTK itself. Have you tested to see whether the bug occurs on a normal form?

**Comment by MGRussell** [comment]
No, the issue does not occur in a normal form. Only in a KryptonForm.

**Comment by MGRussell** [comment]
Ah! There seems to be some issue with the source files there. Check this out: https://github.com/Wagnerp/Krypton-NET-5.470/commits/4.70.524

Those are the commits leading up to the 4.70.524 build. There were indeed numerous changes to to the KryptonForm.cs file, but those are not reflected in the zipped up source code which I agree is identical between the 4.7.0.0 and 4.70.524 versions.

**Comment by Wagnerp** [comment]
The changes seem to refer to the addition of the drop shadow.

**Comment by MGRussell** [comment]
I'm cloning more repos right now since I believe those two source zips were identical except for the 4.70.524 release deleting the packages folder. It would seem that the release binaries and the associated source file are out of sync so the version where the issue was introduced may be later than 4.70.524 (which the source indicates, incorrectly, as being identical to 4.7.0.0).

**Comment by MGRussell** [comment]
Now I can probably confirm something what I suspected above. When I build the binaries from the 4.7.0.0 [source release](https://github.com/Wagnerp/Krypton-NET-5.470/releases/tag/4.7.0.0) I get the issue. When I use the release binaries from there, I do not get the issue.

So this must mean one of two things:
1) There was an upload mistake and the given binaries do not correspond to that source code.
2) Something in my local build pipeline is introducing this issue.

Number 2 seems highly improbable. If possible, could you please send over the binaries you get from a 4.7.0.0 build? But I suspect the real issue is #1. In which case, do you happen to know which source those binaries might have been built from?

---

I've created a couple of related releases:
[This](https://github.com/MGRussell/KryptonIssue/releases/tag/3-downloaded) release is using the provided Krypton binaries. There is no issue.
[This](https://github.com/MGRussell/KryptonIssue/releases/tag/3-built) release is using built Krypton binaries from the 4.7.0.0 source code. This does have the issue.

**Comment by Wagnerp** [comment]
The binaries that you've uploaded still doesn't have any issues on my machine.

**Comment by MGRussell** [comment]
Interesting. Probably an issue that's masked by OS differences then. Running Windows 7 here and on the other machine I tested it on. I'm guessing you're on Windows 10?

**Comment by Wagnerp** [comment]
I'm trying to make a screen recording to show you. Yes I'm running Win 10 1911.

**Comment by Wagnerp** [comment]
I could try it out on my Win 7 VM though...

**Comment by MGRussell** [comment]
That would be much appreciated! [I think] it should appear there for certain if we assume it's being masked by Win10.

**Comment by Wagnerp** [comment]
Might be that something was fixed in the .NET API or OS between 2009 and 2019.

**Comment by MGRussell** [comment]
I am using .NET 4.8 so ostensibly there shouldn't be anything missing on that end. I expect this is probably something quite simple, but missed simply because nobody was using Win7 + atypical rendering contexts (like a GLControl).

However, you do make curious about .NET Core since apparently that involved some new work on forms. I'm curious if this issue emerges there. I'm going to see if I can get this setup on .NET Core and replicate the issue there as well.

**Comment by Wagnerp** [comment]
The toolkit has already been moved to .NET Core, in fact all 4xx repos will be shut down either later this year or by the end of 2021, as the new repo makes it so much easier to support multiple frameworks with one unified codebase.

**Comment by Wagnerp** [comment]
@MGRussell 

I tested it on my Win 7 VM with 16 GB of RAM & still no issues (my host has 32 GB available to it). Can you give the amount that your machines have so I can rule out a memory issue?

**Comment by MGRussell** [comment]
Sure thing. 16GB + 8GB VRAM on one machine, 8GB + 2GB VRAM on the other.

That is really quite surprising that it didn't show up on the VM, but this issue is quite strange. For instance this issue does not appear if the window is full screened. Though it is specifically something about being full screen beyond the size that is doing that. Changing the window to the size of my desktop and the issue is still there.

**Comment by MGRussell** [comment]
Can 100% confirm it's something in KryptonForm. Extending VisualForm directly = no issue.

**Comment by MGRussell** [comment]
I dropped in the old KryptonForm.cs and manually replaced the constants so that that was literally the only file changed. The issue goes away. So I think it's safe to say it's 100% something in there.

Here is a diff of the old and new Krypton: https://www.diffchecker.com/q8TydD9W

**Comment by Smurf-IV** [comment]
> 
> 
> I could try it out on my Win 7 VM though...

@Wagnerp: GLControls via OpenTK, with VM's act very differently, so be careful with any conclusions you draw from that.

@MGRussell : Also in my previous company, I was extensively using Krypton, with splitters, MDI etc, with a GLSurface control (OpenTK - Not latest), that had full interaction of mouse turning etc. And it had to run on all OS's from Win 7 x64 SP1 upwards.

The only issue was with shaders not rendering correctly with some versions of the video driver, and within VM's that emulate Video driver access (like VirtualBox).

As for the Diff, then the thing that "Feels" like it might be an issue is the "Glowing" rendering thing..
@MGRussell: AS you have this in a building and testable state, can you force that to be false always, and see what happens ?

**Comment by MGRussell** [comment]
@Smurf-IV @Wagnerp 

Nailed it, finally. Wagner was spot on from the very beginning. Turns out, for some reason, it's the drop shadows. Doesn't even have anything to do with Krypton other than that they are now enabled by default.  In particular having the program extend Form and enable drop shadows through its own CreateParams results in the issue appearing.

This also explains a lot of the weird behavior like the issue going away when maximized. I expect maximize bypasses whatever system the OS is using for DropShadows since they make no sense. As a fix I would recommend we set the default for DropShadows depending on the OS. Windows 10+ = enabled. Below = disabled.

**Comment by Wagnerp** [comment]
@MGRussell 

Ah that'll be a quick fix, will do it today.

**Comment by MGRussell** [comment]
Great! I *very* much appreciate the help here. I understand how working on something that doesn't even occur on your setup can be vexing.

**Comment by Wagnerp** [comment]
So to be clear:

- Win 10 = **true**
- Win 7, 8 & 8.1 (NT 6) = **false**

Is this correct?

**Comment by MGRussell** [comment]
I'd probably keep it simple by just going 
 - 10+ = true
 - everything else = false

**Comment by Wagnerp** [comment]
i.e

```cs
// Set the UseDropShadow to true
            // Check OS version for compatibility (can be overriden if needed)
            if (Environment.OSVersion.Version.Major == 10)
            {
                UseDropShadow = true;
            }
            else if (Environment.OSVersion.Version.Major <= 6)
            {
                UseDropShadow = false;
            }
```

**Comment by Wagnerp** [comment]
I think we can safely assume that there won't be any versions above **10**

**Comment by MGRussell** [comment]
Looks good. I might go for 

``UseDropShadow = Environment.OSVersion.Version.Major >= 10``

Ah just read your comment. The one nuance here is we're also assuming that the platform is Windows, but that's probably a safe assumption for now. Though there's the hope at least in the future that .NET Core could make Forms cross-platform.

**Comment by Wagnerp** [comment]
The problem with `UseDropShadow = Environment.OSVersion.Version.Major >= 10` is that it doesn't return a bool even if you cast it.

Uploading build 2111 so you can verify that it's fixed [Krypton Toolkit.zip](https://github.com/Wagnerp/Krypton-NET-5.470/files/4044691/Krypton.Toolkit.zip)

**Comment by MGRussell** [comment]
Working perfectly! :+1:

**Comment by Wagnerp** [comment]
Ok, will be uploading the NuGet packages during the day.
