### ISSUE TITLE
Office 2003 and System themes should still display the Form ExtText

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-5.470#27]
Office blue: ![image](https://user-images.githubusercontent.com/2418812/36074251-7e7dd74e-0f35-11e8-8f90-3f0e599cbada.png)

Office 2003 or System: ![image](https://user-images.githubusercontent.com/2418812/36074261-92e4ef7e-0f35-11e8-9f18-808828bb8e93.png)

**Comment by Smurf-IV** [comment]
Could be as simple as Appending the "ExtraText"
and then removing it again if the the theme changes (Edge cases would have to deal with the text being changed when in those themes).
Or as complicated, as "Just fix it"

**Comment by Smurf-IV** [comment]
These themes also do not allow the "Button Extra's" to display in the form title areas.

**Comment by Wagnerp** [comment]
Might be a case of adding the code to the professional themes. By the way, I think that I've found a way to make the kryptonised file dialogs, either use the Win API Codepack or the 'gong-shell' project.
