### ISSUE TITLE
 MouseDown events not subscribed in KryptonTreeView

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-NET-5.470#58]
As title states.

**Comment by Smurf-IV** [comment]
These are redirected as:

        private void OnTreeViewNodeMouseHover(object sender, TreeNodeMouseHoverEventArgs e) => OnNodeMouseHover(e);

        private void OnTreeViewNodeMouseDoubleClick(object sender, TreeNodeMouseClickEventArgs e) => OnNodeMouseDoubleClick(e);

        private void OnTreeViewNodeMouseClick(object sender, TreeNodeMouseClickEventArgs e) => OnNodeMouseClick(e);

**Comment by Wagnerp** [comment]
Might help with the file explorer dialog.
