### ISSUE TITLE
KryptonComboBox does not support a dropdown `BackColor` property

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-NET-5.470#59]
Title is self explanatory.

**Comment by Smurf-IV** [comment]
KryptonComboBox -> StateCommon -> DropBack e-> tc.
or
KryptonComboBox -> StateCommon -> Item -> Back -> etc.

**Comment by Wagnerp** [comment]
Ahh, didn't see. Wondered why I couldn't change this property in the palette designer.
