### ISSUE TITLE
Implement `DrawItem()` event in KryptonComboBox

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-NET-5.470#60]
The `KryptonComboBox` does not appear to have an `DrawItem()` event handler.

**Comment by Smurf-IV** [comment]
Already implemented, but...
The `KryptonComboxBox` redirects the native `OnComboBoxDrawItem(...)` to 

        /// <summary>
        /// Occurs when [draw item].
        /// </summary>
        [Browsable(false)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        public event DrawItemEventHandler DrawItem;

So you will need to attach to that instead.
