### ISSUE TITLE
Phase out Office 2013 Palette

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-NET-5.470#79]
Phase out Office 2013 Palette in favor for a new "Office 365" palette

**Comment by Smurf-IV** [comment]
No..... Keep it, as existing software will be expecting it to be there.
e.g. Professional and office 2003 appear to be similar, **but** need to remain.

**Comment by Wagnerp** [comment]
I've just renamed it, it's still there, but under the `Office 365 - x` name (x means black, blue, silver and white)
