### ISSUE TITLE
Make use of "Built-in" Krypton Tooltip for all Krypton Controls

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-5.470#85]
It has one for the _ButtonSpecs_, so let's implement and allow use for all controls !

**Comment by Smurf-IV** [comment]
2 ways to do this
1) Add it to a base class
2) Add it to every component that needs it

Option 2) does not _feel_ nice!

Option 1) means that things like the `KryptonWrapLabel `will not get it, but things like `KryptonBorderEdge` will for no reason !
![image](https://user-images.githubusercontent.com/2418812/53297337-43888580-3815-11e9-97b1-705802911a35.png)

**Comment by Smurf-IV** [comment]
#86 Why is `KryptonWrapLabel ` derived directory from `Windows.Forms.Label`, and not from `KryptonLabel` ?

**Comment by Cocotteseb** [comment]
Nice addition  ! 
However there is a drawback I do not know how to solve : take for example a KryptonTextbox, add a tooltip. Add a buttonspec to the textbox and add a tooltip  for the button spec.
When the tooltip for the buttonspec appears, the tooltip of the textbox also appears. 

![image](https://user-images.githubusercontent.com/5160288/81457808-ea95da80-9197-11ea-94c3-afea7df96a46.png)

 
Should I create a new issue ?

**Comment by Smurf-IV** [comment]
> Should I create a new issue ?

Yes, probably best to do it that way, and link back to this
