### ISSUE TITLE
Krypton ToolTip positions are useless

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-5.470#90]
The Tooltip position code wants to place the Krypton tooltip under the "Owner" control,
i.e. if you have a `list` or a `treeview`, then the tooltip will appear underneath it - miles away !
It should be "Near the mouse pointer !"

**Comment by Wagnerp** [comment]
Might be that it's not wired into the Krypton/TreeView list item.

**Comment by Smurf-IV** [comment]
The Positioning code forces the tip to that place... But it is overly complicated and get the parent rect multiple times from multiple functions, so will take a while to unscramble !

**Comment by Wagnerp** [comment]
You're not alone, while I was figuring out #82, I found that nothing could be done, as the whole class relied on a key/pair dictionary. So if I messed around with it, then a ripple effect could occur.

**Comment by Smurf-IV** [comment]
I'm going to extend the existing positioning code to be more "WPF" like:

[https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.tooltip.placement?view=netframework-4.7.2](
https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.tooltip.placement?view=netframework-4.7.2)
