### ISSUE TITLE
Docking App loses focus when last RemovePage and RemovePageAndDispose via CloseButtonAction

### ISSUE THREAD

**Issue by richterAl** [Wagnerp/Krypton-NET-5.470#93]
Hello,

I have an issue in the Krypton Docking with RemovePage and RemovePageAndDispose.
After closing the **_last_** Workspace dokument the following behavoirs occur

**`RemovePage`**: Other tabs in the Ribbon are not selectable
**`RemovePageAndDispose`**: The application looses the focus.

The errors only occur if a document in the workspace has the input focus. If a page in the docking edge has the focus, theses issues do not appear.

How to reproduce:

- Open example project _[Krypton Docking Examples]/[Standard Docking]_
- Change the close behavior by changing the `CloseButtonAction` in the `kryptonDockableWorkspace_WorkspaceCellAdding` event to `RemovePage` or `RemovePageAndDispose`
- start application
- close the 2 opened documents in the workspace by clicking on the close button

It is also reproduceable by uncommenting the `kryptonDockableWorkspace_WorkspaceCellAdding` event and setup the corresponding values to the `DefaultCloseRequest` property of the `kryptonDockingManager`.

Best regards.

**Comment by Smurf-IV** [comment]
According to 2 methods, the Test App (As described above) still "Has Focus" !
1st Method: Use the Alt-TAB and it will display that the focus is on the Test-App
2nd Method: I wrote an application that returns that applications that is currently the foregroundWindow, and it shows that it is the Test-App.

BUT,
If you Alt-Tab to an app , then Alt-Tab again, it will step to the next in the list, therefore I think that was currently has the focus in the Test-App is "Not a control"; I'm still not sure what that means !

**Comment by Smurf-IV** [comment]
GetWindowThreadProcessId(GetForegroundWindow(), out uint processID);
    Process currentProcess = Process.GetProcessById((int)processID);
    if (currentProcess != null)
    {
        GetWindowThreadProcessId(this.Handle, out uint thisThreadId);
        if (string.IsNullOrWhiteSpace(currentProcess.MainWindowTitle))
            listBox1.Items.Add(currentProcess.ProcessName);
        else
        {
            listBox1.Items.Add(currentProcess.MainWindowTitle);
         }
    }

**Comment by Smurf-IV** [comment]
This problem can also be reproduced in the Memo Editor from in the Workspace Examples.
Change the function to the following and then close the workspace cells:

        private void kryptonWorkspace_WorkspaceCellAdding(object sender, WorkspaceCellEventArgs e)
        {
            e.Cell.Button.CloseButtonAction = CloseButtonAction.RemovePageAndDispose;

            // Do not need the secondary header for header modes
            e.Cell.Header.HeaderVisibleSecondary = false;
        }

**Comment by Smurf-IV** [comment]
BUT, 
As these are Navigator cells, then Making the similar change in the "Navigator Pallettes" Example app does not cause the Loss of focus, because the Parent control is visible ..

So it must be something to do with the wrapping of these controls in the DockableWorkspace.
