### ISSUE TITLE
Nuget Package when viewed within Visual Studio does not have a License field

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-5.470#97]
## Compare:
![image](https://user-images.githubusercontent.com/2418812/54085844-5c775780-433a-11e9-85f9-598c00e15c42.png)
---------------------------------------------------------------------------------------

## With:
![image](https://user-images.githubusercontent.com/2418812/54085858-8a5c9c00-433a-11e9-897b-347dccd44d1f.png)
---------------------------------------------------------------------------------------

**Comment by Smurf-IV** [comment]
oh, And can it also have Themes in the Tags as well ;-)

**Comment by Wagnerp** [comment]
Will fix that on the next NuGet release. I still need to find a VS extension to manage these, as I've been relying on NuGet Package Explorer.

**Comment by Smurf-IV** [comment]
Please also include the *.xml files in the nuget package

**Comment by Wagnerp** [comment]
Would that be the theme files from the extended toolkit?

**Comment by Smurf-IV** [comment]
No, They are created during compile to aid intelli-sense for the API's etc.
They have the same name as the dll, but with the `xml` extension

**Comment by Wagnerp** [comment]
Ahh, ok will upload them in a `.1` release.

**Comment by Wagnerp** [comment]
Done, will update other packages tomorrow.
